language: python
python:
    - "3.5"
    - "3.6"

env:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0

install:
- pip install -r requirements.txt
- yes | pip uninstall Django
- pip install Django==$DJANGO_VERSION
- pip install --user black

script:
- coverage run manage.py test
- black --check .

after_success:
- coverage report
