language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

env:
  global:
    - SECRET_KEY=superSecretKey
  matrix:
    - DJANGO_VERSION=1.10 DRF_VERSION=3.5 DRF_VERSION=3.6 DRF_VERSION=3.7 DRF_VERSION=3.8
    - DJANGO_VERSION=1.11 DRF_VERSION=3.5 DRF_VERSION=3.6 DRF_VERSION=3.7 DRF_VERSION=3.8
    - DJANGO_VERSION=2.0 DRF_VERSION=3.5 DRF_VERSION=3.6 DRF_VERSION=3.7 DRF_VERSION=3.8

matrix:
  allow_failures:
  - python: "3.7-dev"

install:
- pip install -r requirements.txt
- yes | pip uninstall Django
- pip install Django==$DJANGO_VERSION
- pip install djangorestframework==$DRF_VERSION
- pip install black==18.6b1 || true

script:
- black --check . || true
- python manage.py test
